name: myfirstaction
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
    - name: Print "Greetings"
      run: echo "Hello World"
    - name: Print congrats
      run: echo "hello from Accenture"
