name: myfirstaction
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - name: echo message
      run: echo "Hello, ${{ vars.MY_NAME }}"
    - name: Surname
      run: echo "Surname - ${{ secrets_MY_SURNAME }}"
      
      
      
